/**********************************************************************************************************************
 * \file GPIO_LED_Button.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"
#include "Bsp.h"
#include "GPIO_RTC.h"

#define WAIT_TIME 2
#define WAIT_TIME_10ms 10

/*********************************************************************************************************************/
/*-----------------------------------------------------Macros--------------------------------------------------------*/
/*********************************************************************************************************************/
#define SCLK    &MODULE_P14, 10 /* Port pin for the sclk  */
#define SERIAL  &MODULE_P14, 8  /* Port pin for the io  */
#define CE      &MODULE_P14, 6  /* Port pin for the ce  */

int clock_data[8];
int temp_byte[8];
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/



/* Function to configure the port pins for the push button and the LED */
void init_GPIOs(void)
{
    IfxPort_setPinMode(SCLK, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(CE, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(SERIAL, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinState(SCLK, IfxPort_State_low);
    IfxPort_setPinState(CE, IfxPort_State_low);
    IfxPort_setPinState(SERIAL, IfxPort_State_low);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));
}

void Write_Byte(int content)
{
    IfxPort_setPinMode(SERIAL, IfxPort_Mode_outputPushPullGeneral);
    for (int i=0;i<8;i++){
             int x = (content & (1 << i));  //Write to Address
             Send_Bit(x);
             SCLK_Pulse_LH();
        }
}

void Read_Byte(int addr)
{
    int temp = 0;
    Write_Byte(addr);
    IfxPort_setPinMode(SERIAL, IfxPort_Mode_inputNoPullDevice);
    for (int j = 0; j < 8; j++)
    {
        SCLK_Pulse_HL();
        temp >>= 1;
        if ((IfxPort_getPinState(SERIAL)) == 0x01)
        {
            temp |= 128;
        }
        else
        {
            temp &= 127;
        }
    }
}

void Read_Burst(void)
{
    CE_On();
    Write_Byte(ADR_RD_BURST);
    IfxPort_setPinMode(SERIAL, IfxPort_Mode_inputNoPullDevice); //set as input for receiving data
    int temp;
    for (int i = 0; i < 8; i++)
    {
        temp = 0;
        for (int j = 0; j < 8; j++)
        {
            SCLK_Pulse_HL();
            temp >>= 1;
            if ((IfxPort_getPinState(SERIAL)) == 0x01)
            {
                temp |= 128;
            }
            else
            {
                temp &= 127;
            }
        }
        clock_data[i] = temp;
    }
    CE_Off();
}

void SCLK_Pulse_HL(void)
{
    IfxPort_setPinState(SCLK, IfxPort_State_high);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));
    IfxPort_setPinState(SCLK, IfxPort_State_low);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));
}

void SCLK_Pulse_LH(void)
{
    IfxPort_setPinState(SCLK, IfxPort_State_low);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));
    IfxPort_setPinState(SCLK, IfxPort_State_high);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));
}

void Send_Bit (unsigned int value)
{
    if (value != 0){
        IfxPort_setPinState(SERIAL, IfxPort_State_high);}
    else {
        IfxPort_setPinState(SERIAL, IfxPort_State_low);
    }
}

void CE_On (void)
{
    IfxPort_setPinState(CE, IfxPort_State_high);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));
}

void CE_Off (void)
{
    IfxPort_setPinState(CE, IfxPort_State_low);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));
}

void settime(void)
{
    CE_On();
    Write_Byte(ADR_WR_CREG);  //goto control register
    Write_Byte(0x00);         //disable write protect
    CE_Off();
    CE_On();
    Write_Byte(ADR_WR_TCR);  //Go to Trickle charge register
    Write_Byte(171);  //Enable Charger, 2 diodes, 8kOhm
    CE_Off();
    CE_On();
    Write_Byte(ADR_WR_SEC);  //Go to seconds register
    Write_Byte(0x00);  //set as..
    CE_Off();
    CE_On();
    Write_Byte(ADR_WR_MIN);  //Go to minute register
    Write_Byte(0x31);  //set as..
    CE_Off();
    CE_On();
    Write_Byte(ADR_WR_HR);  //Go to hour register
    Write_Byte(0x11);  //set as..
    CE_Off();
    CE_On();
    Write_Byte(ADR_WR_DATE);  //Go to date register
    Write_Byte(0x14);  //set as..
    CE_Off();
    CE_On();
    Write_Byte(ADR_WR_MON);  //Go to month register
    Write_Byte(0x09);  //set as..
    CE_Off();
    CE_On();
    Write_Byte(ADR_WR_DAY);  //Go to day register
    Write_Byte(0x02);  //set as..
    CE_Off();
    CE_On();
    Write_Byte(ADR_WR_YR);  //Go to year register
    Write_Byte(0x21);  //set as..21
    CE_Off();
    CE_On();
    Read_Burst();
    CE_Off();
}
//IfxPort_getPinState(BUTTON) == 0
//IfxPort_setPinState(LED, IfxPort_State_high);
//IfxPort_setPinState(LED, IfxPort_State_low);
